image: docker
services:
  - docker:dind

variables:
  REGISTRY_REPO: registry.gitlab.com/gusisoft/onelike/mailer-service
  MAILER: mailer
  SWAGGER: mailer-swagger

stages:
  - tests
  - registry
  - deploy

Testing:
  stage: tests
  only:
    - devel
  before_script:
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
  script:
    - docker-compose -f docker-compose-dev.yml up -d --build
    - docker-compose -f docker-compose-dev.yml run mailer flake8 project
    - docker-compose -f docker-compose-dev.yml run mailer python manage.py cov
  after_script:
    - docker-compose -f docker-compose-dev.yml down

Mailer Service:
  stage: registry
  only:
    - stage
    - master
  before_script:
    - apk add --no-cache git
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - export TAG=${CI_COMMIT_REF_NAME}_$COMMIT_TIME
    - docker login -u gitlab-ci-token -p $DOCKER_TOKEN registry.gitlab.com
    - export MAIN_REPO="https://${GITLAB_USER}:${GITLAB_PASSWORD}@gitlab.com/gusisoft/OneLike/mailer-service.git"
    - export MAILER_REPO="${MAIN_REPO}#${CI_COMMIT_REF_NAME}"
  script:
    - docker build $MAILER_REPO -t $MAILER:$CI_COMMIT_SHA -f Dockerfile-${CI_COMMIT_REF_NAME}
    - docker tag $MAILER:$CI_COMMIT_SHA $REGISTRY_REPO/$MAILER:$TAG
    - docker push $REGISTRY_REPO/$MAILER:$TAG
  after_script:
    - docker image rm -f $(docker images registry.gitlab.com/gusisoft/onelike/mailer-service/mailer -q)

Mailer Swagger:
  stage: registry
  only:
    - stage
    - master
  before_script:
    - apk add --no-cache git
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - export TAG=${CI_COMMIT_REF_NAME}_$COMMIT_TIME
    - docker login -u gitlab-ci-token -p $DOCKER_TOKEN registry.gitlab.com
    - export MAIN_REPO="https://${GITLAB_USER}:${GITLAB_PASSWORD}@gitlab.com/gusisoft/OneLike/mailer-service.git"
    - export SWAGGER_REPO="${MAIN_REPO}#${CI_COMMIT_REF_NAME}:swagger"
  script:
    - docker build $SWAGGER_REPO -t $SWAGGER:$CI_COMMIT_SHA -f Dockerfile
    - docker tag $SWAGGER:$CI_COMMIT_SHA $REGISTRY_REPO/$SWAGGER:$TAG
    - docker push $REGISTRY_REPO/$SWAGGER:$TAG
  after_script:
    - docker image rm -f $(docker images registry.gitlab.com/gusisoft/onelike/mailer-service/mailer-swagger -q)

Deploy Stage:
  stage: deploy
  only:
    - stage
  before_script:
    - apk add --no-cache openssh-client git
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - export TAG=${CI_COMMIT_REF_NAME}_$COMMIT_TIME
    - rm -rf ~/.ssh
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - sh ./${CI_COMMIT_REF_NAME}-deploy.sh

Deploy Production:
  stage: deploy
  only:
    - master
  before_script:
    - apk add --no-cache openssh-client git
    - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    - export TAG=${CI_COMMIT_REF_NAME}_$COMMIT_TIME
    - rm -rf ~/.ssh
    - mkdir -p ~/.ssh
    - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - sh ./${CI_COMMIT_REF_NAME}-deploy.sh
